### ISSUE TITLE
Can not create a new dashboard with the name which used by a deleted dashboard

### ISSUE THREAD

**Issue by liangjingyang** [merico-dev/table#633]
![L7xuLZq9uw](https://user-images.githubusercontent.com/2056705/218476079-a9daa4cd-d8ba-4ffb-a203-b7c621568703.jpg)

Reproduce steps:

1. Create a new dashboard named `test`.
2. Delete the `test` dashboard.
3. Create another new dashboard named `test` again.
4. The above error occurred.

**Comment by miguel-lansdorf** [comment]
Deleting  a dashboard only changes the is_removed field to true. It does not actually delete the record from the database.
Trying to add a new dashboard with the same name (and is_preset field is also the same) will result in a unique key violation as seen in the error message.

Possible solutions: 
1. Drop the unique key index. Not recommended because it will require code changes and makes finding a specific dashboard more difficult because there might be multiple dashboards with the same properties.
2. Actually delete the dashboard from the database. Recommended because it just requires a small code change (logic for deleting dashboards)
3. Use a unique name for each dashboard (requires no changes to the code, but might make the user experience less convenient.

**Comment by liangjingyang** [comment]
I just propose another 2 solutions:

4. Use an unique index with where clause, only index the dashboard by name with is_removed = true. (MySQL doesn't support it)

5. Update the name together, append a random suffix after the name when updating the is_removed to true.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
